// <auto-generated />
using System;
using LibraryManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260113015240_AddDueDateInBorrowTable")]
    partial class AddDueDateInBorrowTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Myrtice Casper",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "0995764628211",
                            IsDeleted = false,
                            StockQuantity = 31,
                            Title = "Gorgeous Metal Car",
                            URL = "https://picsum.photos/640/480/?image=713"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Hope Kuhlman",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "2404055566098",
                            IsDeleted = false,
                            StockQuantity = 11,
                            Title = "Fantastic Cotton Shirt",
                            URL = "https://picsum.photos/640/480/?image=646"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Leilani Thiel",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3104986968822",
                            IsDeleted = false,
                            StockQuantity = 13,
                            Title = "Handmade Soft Pants",
                            URL = "https://picsum.photos/640/480/?image=696"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Kassandra Cremin",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "0805725451508",
                            IsDeleted = false,
                            StockQuantity = 28,
                            Title = "Awesome Fresh Towels",
                            URL = "https://picsum.photos/640/480/?image=843"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Johnpaul Dietrich",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9598773334824",
                            IsDeleted = false,
                            StockQuantity = 23,
                            Title = "Small Cotton Tuna",
                            URL = "https://picsum.photos/640/480/?image=871"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Lillian O'Keefe",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3145285018122",
                            IsDeleted = false,
                            StockQuantity = 18,
                            Title = "Awesome Wooden Shoes",
                            URL = "https://picsum.photos/640/480/?image=65"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Nikko Bayer",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9110332375897",
                            IsDeleted = false,
                            StockQuantity = 43,
                            Title = "Sleek Fresh Bike",
                            URL = "https://picsum.photos/640/480/?image=37"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Kristy Willms",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "2224351423693",
                            IsDeleted = false,
                            StockQuantity = 29,
                            Title = "Refined Wooden Table",
                            URL = "https://picsum.photos/640/480/?image=794"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Chet Thompson",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "5135912243346",
                            IsDeleted = false,
                            StockQuantity = 40,
                            Title = "Intelligent Steel Pants",
                            URL = "https://picsum.photos/640/480/?image=685"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Mohammad Runte",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "1704992416878",
                            IsDeleted = false,
                            StockQuantity = 36,
                            Title = "Handcrafted Frozen Chicken",
                            URL = "https://picsum.photos/640/480/?image=258"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Jovanny Dach",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3999913970234",
                            IsDeleted = false,
                            StockQuantity = 21,
                            Title = "Small Fresh Chicken",
                            URL = "https://picsum.photos/640/480/?image=693"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Laurel Zieme",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9708552948825",
                            IsDeleted = false,
                            StockQuantity = 28,
                            Title = "Licensed Wooden Sausages",
                            URL = "https://picsum.photos/640/480/?image=162"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Hyman Schamberger",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "6271441895898",
                            IsDeleted = false,
                            StockQuantity = 27,
                            Title = "Intelligent Fresh Computer",
                            URL = "https://picsum.photos/640/480/?image=83"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Hunter Johnston",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9359291094900",
                            IsDeleted = false,
                            StockQuantity = 41,
                            Title = "Generic Fresh Keyboard",
                            URL = "https://picsum.photos/640/480/?image=528"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Gaston Aufderhar",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "4498982638377",
                            IsDeleted = false,
                            StockQuantity = 1,
                            Title = "Handcrafted Steel Sausages",
                            URL = "https://picsum.photos/640/480/?image=712"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Steve Kuphal",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3084684215599",
                            IsDeleted = false,
                            StockQuantity = 21,
                            Title = "Gorgeous Soft Cheese",
                            URL = "https://picsum.photos/640/480/?image=818"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Alaina Hintz",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "7571124490822",
                            IsDeleted = false,
                            StockQuantity = 44,
                            Title = "Sleek Cotton Chicken",
                            URL = "https://picsum.photos/640/480/?image=50"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Corrine Bruen",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3947239203819",
                            IsDeleted = false,
                            StockQuantity = 27,
                            Title = "Fantastic Rubber Table",
                            URL = "https://picsum.photos/640/480/?image=800"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Elias Hoppe",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "4030629876904",
                            IsDeleted = false,
                            StockQuantity = 46,
                            Title = "Handmade Plastic Tuna",
                            URL = "https://picsum.photos/640/480/?image=503"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Shanna Stark",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "2145275519098",
                            IsDeleted = false,
                            StockQuantity = 42,
                            Title = "Licensed Wooden Chips",
                            URL = "https://picsum.photos/640/480/?image=150"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Angeline Barton",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "4053486859637",
                            IsDeleted = false,
                            StockQuantity = 23,
                            Title = "Incredible Rubber Pants",
                            URL = "https://picsum.photos/640/480/?image=850"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Reuben Walker",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "6377508626273",
                            IsDeleted = false,
                            StockQuantity = 43,
                            Title = "Gorgeous Rubber Cheese",
                            URL = "https://picsum.photos/640/480/?image=1015"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Brooks Klein",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "1791371674783",
                            IsDeleted = false,
                            StockQuantity = 7,
                            Title = "Intelligent Rubber Car",
                            URL = "https://picsum.photos/640/480/?image=580"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Prince Kautzer",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "9068783908648",
                            IsDeleted = false,
                            StockQuantity = 19,
                            Title = "Small Plastic Bacon",
                            URL = "https://picsum.photos/640/480/?image=671"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Gene Shanahan",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "8187832753884",
                            IsDeleted = false,
                            StockQuantity = 36,
                            Title = "Tasty Cotton Towels",
                            URL = "https://picsum.photos/640/480/?image=290"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Jarod Koss",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "3168832133673",
                            IsDeleted = false,
                            StockQuantity = 49,
                            Title = "Rustic Wooden Keyboard",
                            URL = "https://picsum.photos/640/480/?image=471"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Zetta Harris",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "6546982986825",
                            IsDeleted = false,
                            StockQuantity = 46,
                            Title = "Licensed Wooden Pizza",
                            URL = "https://picsum.photos/640/480/?image=89"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Tom MacGyver",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "1041713217025",
                            IsDeleted = false,
                            StockQuantity = 8,
                            Title = "Handcrafted Granite Chair",
                            URL = "https://picsum.photos/640/480/?image=149"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Sean Anderson",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "0326436558206",
                            IsDeleted = false,
                            StockQuantity = 22,
                            Title = "Licensed Soft Chips",
                            URL = "https://picsum.photos/640/480/?image=1016"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Vallie Terry",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ISBN = "4971661916954",
                            IsDeleted = false,
                            StockQuantity = 46,
                            Title = "Generic Wooden Ball",
                            URL = "https://picsum.photos/640/480/?image=173"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Borrowed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Borrows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 23,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 2,
                            BookId = 20,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            BookId = 13,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 23,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            BookId = 15,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 9,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            BookId = 30,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 8
                        },
                        new
                        {
                            Id = 8,
                            BookId = 21,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 2,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            BookId = 18,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            BookId = 18,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            BookId = 2,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            BookId = 8,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            BookId = 13,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            BookId = 29,
                            BorrowDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "Borrowed",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sunt recusandae molestias et quia expedita culpa doloribus enim occaecati.",
                            IsDeleted = false,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quia dolor est id facilis ipsam autem molestias.",
                            IsDeleted = false,
                            Name = "Industrial"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unde rerum distinctio velit quidem iure.",
                            IsDeleted = false,
                            Name = "Baby"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sapiente qui aspernatur.",
                            IsDeleted = false,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non similique fugit ab.",
                            IsDeleted = false,
                            Name = "Grocery"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 28,
                            Comment = "Nulla ex et fuga qui.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 5,
                            URL = "https://picsum.photos/640/480/?image=19",
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            BookId = 6,
                            Comment = "Nisi quam sapiente ut earum esse et nesciunt.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 4,
                            URL = "https://picsum.photos/640/480/?image=485",
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            BookId = 11,
                            Comment = "Consequatur veritatis tempore molestiae at sit dolor ipsa.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=306",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            BookId = 23,
                            Comment = "Officiis velit unde maiores aut.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 2,
                            URL = "https://picsum.photos/640/480/?image=727",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookId = 16,
                            Comment = "Temporibus cupiditate a perspiciatis numquam placeat tempore et accusantium.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=382",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            BookId = 19,
                            Comment = "Nesciunt voluptatem sed vero est veritatis libero nostrum perspiciatis.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=875",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            BookId = 17,
                            Comment = "Ea nesciunt et autem corporis.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 4,
                            URL = "https://picsum.photos/640/480/?image=92",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            BookId = 27,
                            Comment = "Error nostrum id magni facilis odit impedit et at.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 5,
                            URL = "https://picsum.photos/640/480/?image=980",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            BookId = 25,
                            Comment = "Nihil dignissimos quia et reiciendis aliquid alias magni.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 1,
                            URL = "https://picsum.photos/640/480/?image=710",
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            Comment = "Aliquam quas laboriosam ut.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 5,
                            URL = "https://picsum.photos/640/480/?image=279",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            BookId = 13,
                            Comment = "Praesentium sed facilis odio ut.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 2,
                            URL = "https://picsum.photos/640/480/?image=358",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            BookId = 7,
                            Comment = "Voluptatem qui libero eos ipsa vel molestiae perspiciatis.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=922",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            BookId = 14,
                            Comment = "Omnis et blanditiis error excepturi eos sunt incidunt cum.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 2,
                            URL = "https://picsum.photos/640/480/?image=167",
                            UserId = 8
                        },
                        new
                        {
                            Id = 14,
                            BookId = 11,
                            Comment = "Ut qui non eveniet quis temporibus omnis porro repellendus.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 4,
                            URL = "https://picsum.photos/640/480/?image=1065",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            BookId = 20,
                            Comment = "Debitis unde at sed ipsum.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=323",
                            UserId = 6
                        },
                        new
                        {
                            Id = 16,
                            BookId = 27,
                            Comment = "Porro doloribus a voluptatum rem perferendis quia aut ea cupiditate.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=558",
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            BookId = 3,
                            Comment = "Et quia inventore eos officiis molestiae numquam suscipit labore.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 3,
                            URL = "https://picsum.photos/640/480/?image=274",
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            BookId = 4,
                            Comment = "Aut maiores accusantium consequatur dolorum sit ullam eum beatae.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 1,
                            URL = "https://picsum.photos/640/480/?image=571",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            BookId = 24,
                            Comment = "Alias rerum repellendus exercitationem ipsam suscipit tempore nisi consequatur vel.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 4,
                            URL = "https://picsum.photos/640/480/?image=283",
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            BookId = 30,
                            Comment = "Quia nisi corrupti dolor quasi et sed ex.",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Rating = 4,
                            URL = "https://picsum.photos/640/480/?image=543",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_1",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Tito_Hessel@hotmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Filomena Ledner",
                            NormalizedEmail = "TITO_HESSEL@HOTMAIL.COM",
                            NormalizedUserName = "TITO_HESSEL@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_1",
                            TwoFactorEnabled = false,
                            UserName = "Tito_Hessel@hotmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_2",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Herman.Rohan@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Devyn Hermiston",
                            NormalizedEmail = "HERMAN.ROHAN@GMAIL.COM",
                            NormalizedUserName = "HERMAN.ROHAN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_2",
                            TwoFactorEnabled = false,
                            UserName = "Herman.Rohan@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_3",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Gerson.Mueller@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Della Hahn",
                            NormalizedEmail = "GERSON.MUELLER@GMAIL.COM",
                            NormalizedUserName = "GERSON.MUELLER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_3",
                            TwoFactorEnabled = false,
                            UserName = "Gerson.Mueller@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_4",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Dedrick_Lynch@hotmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Aiyana Dietrich",
                            NormalizedEmail = "DEDRICK_LYNCH@HOTMAIL.COM",
                            NormalizedUserName = "DEDRICK_LYNCH@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_4",
                            TwoFactorEnabled = false,
                            UserName = "Dedrick_Lynch@hotmail.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_5",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Caterina43@yahoo.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Noel MacGyver",
                            NormalizedEmail = "CATERINA43@YAHOO.COM",
                            NormalizedUserName = "CATERINA43@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_5",
                            TwoFactorEnabled = false,
                            UserName = "Caterina43@yahoo.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_6",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Clair_Heathcote28@yahoo.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Winona Reynolds",
                            NormalizedEmail = "CLAIR_HEATHCOTE28@YAHOO.COM",
                            NormalizedUserName = "CLAIR_HEATHCOTE28@YAHOO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_6",
                            TwoFactorEnabled = false,
                            UserName = "Clair_Heathcote28@yahoo.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_7",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Kelley.Abbott13@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Antonette Rogahn",
                            NormalizedEmail = "KELLEY.ABBOTT13@GMAIL.COM",
                            NormalizedUserName = "KELLEY.ABBOTT13@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_7",
                            TwoFactorEnabled = false,
                            UserName = "Kelley.Abbott13@gmail.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_8",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alize12@hotmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Renee White",
                            NormalizedEmail = "ALIZE12@HOTMAIL.COM",
                            NormalizedUserName = "ALIZE12@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_8",
                            TwoFactorEnabled = false,
                            UserName = "Alize12@hotmail.com"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_9",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Ewell_Kuvalis25@hotmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Marlen Schmitt",
                            NormalizedEmail = "EWELL_KUVALIS25@HOTMAIL.COM",
                            NormalizedUserName = "EWELL_KUVALIS25@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_9",
                            TwoFactorEnabled = false,
                            UserName = "Ewell_Kuvalis25@hotmail.com"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER_CONCUR_10",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Dewitt.McClure@hotmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            Name = "Dakota Collins",
                            NormalizedEmail = "DEWITT.MCCLURE@HOTMAIL.COM",
                            NormalizedUserName = "DEWITT.MCCLURE@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9v9p6X3GjS5I5f6m4g5r9k5l5t5y5u5i5o5p5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "USER_STAMP_10",
                            TwoFactorEnabled = false,
                            UserName = "Dewitt.McClure@hotmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "ROLE_STAMP_1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "ROLE_STAMP_2",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Borrow", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Book", "Book")
                        .WithMany("borrows")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany("Borrows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Review", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LibraryManagement.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("borrows");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("Borrows");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
